- name: Allow SSH from 103.136.58.0/24
  ufw:
    rule: allow
    from: 103.136.58.0/24
    port: ssh
    state: enabled
- name: Allow 443 from public
  ufw:
    rule: allow
    from: 0.0.0.0/0
    port: https
    state: enabled
- name: Allow 80 from public
  ufw:
    rule: allow
    from: 0.0.0.0/0
    port: http
    state: enabled
