---
- name: Download K3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'

- name: Run K3s install script
  command: >
    sh /tmp/k3s_install.sh agent
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    K3S_URL: "{{ k3s_url }}"
    K3S_TOKEN: "{{ k3s_token }}"

- name: Ensure k3s-agent service is enabled and started
  systemd:
    name: k3s-agent
    state: started
    enabled: yes
